# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
description:  This blog is only intended to  mark down notes while learning.
markdown: kramdown
# Setup
title:               Yijun Ge's blog
tagline:             '         To learn'
url:                 https://yijungepurdue.com
paginate:            5

# About/contact
author:
  name:              Yijun Ge
  url:               yijungepurdue.com
  email:             yijungehust@gmail.com

# Custom vars
version:             1.0.0

github:
  repo: https://github.com/yijunge/blog

comment:
	disqus: yijunge  
