# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               blog
tagline:             'my blog'
url:                 http://github.com/yijunge/blog
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yijun Ge
  url:               https://github.com/yijunge
  email:             yijungehust@gmail.com

# Custom vars
version:             1.0.0
