# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Yijun Ge's blog
tagline:             ''
url:                 yijungepurdue.com
baseurl:             yijungepurdue.com
paginate:            5

# About/contact
author:
  name:              Yijun Ge
  url:               yijungepurdue.com
  email:             yijungehust@gmail.com

# Custom vars
version:             1.0.0

github:
  repo: https://github.com/yijunge/blog
